//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public int id_admin { get; set; }
        public string nombre_completo { get; set; }
        public string nombre_admin { get; set; }
        public string clave { get; set; }
        public string email_admin { get; set; }
    }
}
